services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./flights.json:/data/flights.json:ro
    environment:
      - FLIGHTS_DATASET_PATH=/data/flights.json

  frontend:
    build:
      context: ./frontend
      secrets:
        - npmrc
    ports:
      - "3000:80"
    depends_on:
      - backend

secrets:
  npmrc:
    file: ${HOME}/.npmrc
